### ISSUE TITLE
using this on game today

### ISSUE THREAD

**Issue by miguelshta21** [AmmarkoV/VisualBotNGine#1]
hello is possible and still useable nowdays have any chanse to contact you on discord?

**Comment by AmmarkoV** [comment]
Hello, 
The code should compile fine, however I expect that the game targeted ( Bejeweled Blitz  https://www.youtube.com/watch?v=lzMLwwfkczU ) has changed its layout so it will require tweaking to work again. Unfortunately due to a large number of tasks I have to do I am not available and I am not planning to work on this project for the foreseeable future.. :(
Sorry

**Comment by miguelshta21** [comment]
thank you anyways i wanna make it work for other game: tibia

**Comment by AmmarkoV** [comment]
Good luck!
